"""create education_stat table

Revision ID: 2c44e4938762
Revises: 749a12d0fc47
Create Date: 2025-09-29 20:12:18.839353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel  # added

# revision identifiers, used by Alembic.
revision: str = '2c44e4938762'
down_revision: Union[str, None] = '749a12d0fc47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_stat',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('county', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'year', 'county', name='uq_education_stat_src_year_cnty')
    )
    op.create_index(op.f('ix_education_stat_county'), 'education_stat', ['county'], unique=False)
    op.create_index(op.f('ix_education_stat_source'), 'education_stat', ['source'], unique=False)
    op.create_index(op.f('ix_education_stat_year'), 'education_stat', ['year'], unique=False)
    op.alter_column('donation', 'donation_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('donation', 'progress',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # keep profile.user_id unchanged as UUID
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('donation', 'progress',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('donation', 'donation_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_education_stat_year'), table_name='education_stat')
    op.drop_index(op.f('ix_education_stat_source'), table_name='education_stat')
    op.drop_index(op.f('ix_education_stat_county'), table_name='education_stat')
    op.drop_table('education_stat')
    # ### end Alembic commands ###
