"""fix_profile_user_id_type

Revision ID: e84e6a362d75
Revises: d0b5c13235bd
Create Date: 2025-10-20 13:28:39.524739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e84e6a362d75'
down_revision: Union[str, None] = '2c44e4938762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_wide_edu_B_1_4_county")
    op.execute("DROP INDEX IF EXISTS ix_wide_edu_B_1_4_year")
    op.execute("DROP TABLE IF EXISTS wide_edu_B_1_4 CASCADE")
    op.execute("DROP INDEX IF EXISTS ix_wide_faraway3_code")
    op.execute("DROP INDEX IF EXISTS ix_wide_faraway3_county")
    op.execute("DROP INDEX IF EXISTS ix_wide_faraway3_year")
    op.execute("DROP TABLE IF EXISTS wide_faraway3 CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wide_faraway3',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('學年度', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('縣市名稱', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('鄉鎮市區', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('學生等級', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('本校代碼', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('本校名稱', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('分校分班名稱', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('公/私立', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('地區屬性', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('班級數', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('男學生數[人]', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('女學生數[人]', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('原住民學生比率', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('上學年男畢業生數[人]', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('上學年女畢業生數[人]', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='wide_faraway3_pkey'),
    sa.UniqueConstraint('學年度', '本校代碼', '分校分班名稱', name='uq_wide_faraway_year_code_branch', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_wide_faraway3_year', 'wide_faraway3', ['學年度'], unique=False)
    op.create_index('ix_wide_faraway3_county', 'wide_faraway3', ['縣市名稱'], unique=False)
    op.create_index('ix_wide_faraway3_code', 'wide_faraway3', ['本校代碼'], unique=False)
    op.create_table('wide_edu_B_1_4',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('學年度', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('縣市別', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('幼兒園[人]', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('國小[人]', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('國中[人]', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('高級中等學校-普通科[人]', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('高級中等學校-專業群科[人]', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('高級中等學校-綜合高中[人]', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('高級中等學校-實用技能學程[人]', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('高級中等學校-進修部[人]', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('大專校院(全部計入校本部)[人]', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('大專校院(跨縣市教學計入所在地縣市)[人]', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('宗教研修學院[人]', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('國民補習及大專進修學校及空大[人]', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('特殊教育學校[人]', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='wide_edu_B_1_4_pkey'),
    sa.UniqueConstraint('學年度', '縣市別', name='uq_wide_edu_year_county', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_wide_edu_B_1_4_year', 'wide_edu_B_1_4', ['學年度'], unique=False)
    op.create_index('ix_wide_edu_B_1_4_county', 'wide_edu_B_1_4', ['縣市別'], unique=False)
    # ### end Alembic commands ###
